// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recap.Models.Context;

#nullable disable

namespace Recap.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recap.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "alice.dupont@email.com",
                            Firstname = "Alice",
                            Lastname = "Dupont",
                            Password = "Jt8L$ndm&kFq24cS"
                        },
                        new
                        {
                            ID = 2,
                            Email = "bob.martin@email.com",
                            Firstname = "Bob",
                            Lastname = "Martin",
                            Password = "5Gh#zBvKw3PxYrE"
                        },
                        new
                        {
                            ID = 3,
                            Email = "charlie.nguyen@email.com",
                            Firstname = "Charlie",
                            Lastname = "Nguyen",
                            Password = "fT7#eRm2QxLz9Dy$"
                        },
                        new
                        {
                            ID = 4,
                            Email = "david.lee@email.com",
                            Firstname = "David",
                            Lastname = "Lee",
                            Password = "V6b$UwPcNz @hM8xK"
                        },
                        new
                        {
                            ID = 5,
                            Email = "emma.garcia@email.com",
                            Firstname = "Emma",
                            Lastname = "Garcia",
                            Password = "aH5%kXjL9$qBm2W"
                        },
                        new
                        {
                            ID = 6,
                            Email = "frank.chen@email.com",
                            Firstname = "Frank",
                            Lastname = "Chen",
                            Password = "qJ9@fM8cWu5$xLrE"
                        },
                        new
                        {
                            ID = 7,
                            Email = "grace.wong@email.com",
                            Firstname = "Grace",
                            Lastname = "Wong",
                            Password = "7Km&zRb#vGy2hNj"
                        },
                        new
                        {
                            ID = 8,
                            Email = "henry.zhang@email.com",
                            Firstname = "Henry",
                            Lastname = "Zhang",
                            Password = "T4c#nSv@wGj2RkF"
                        },
                        new
                        {
                            ID = 9,
                            Email = "isabella.lopez@email.com",
                            Firstname = "Isabella",
                            Lastname = "Lopez",
                            Password = "H8f$kL3q#sVp9Xy"
                        },
                        new
                        {
                            ID = 10,
                            Email = "jack.kim@email.com",
                            Firstname = "Jack",
                            Lastname = "Kim",
                            Password = "3ZgY*6tLx#pVfDhN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
